puts "Seeding continents..."

africa = Continent.create!(name: "Africa")
antarctica = Continent.create!(name: "Antarctica")
asia = Continent.create!(name: "Asia")
europe = Continent.create!(name: "Europe")
north_america = Continent.create!(name: "North America")
oceania = Continent.create!(name: "Oceania")
south_america = Continent.create!(name: "South America")

puts "Done seeding continents..."

puts "Seeding countries..."

#Asia

afghanistan = Country.create!(name: "Afghanistan", continent_id: asia.id)
armenia = Country.create!(name: "Armenia", continent_id: asia.id)
azerbaijan = Country.create!(name: "azerbaijan", continent_id: asia.id)
bahrain = Country.create!(name: "Bahrain", continent_id: asia.id)
bangladesh = Country.create!(name: "Bangladesh", continent_id: asia.id)
bhutan = Country.create!(name: "Bhutan", continent_id: asia.id)
brunei = Country.create!(name: "Brunei", continent_id: asia.id)
cambodia = Country.create!(name: "Cambodia", continent_id: asia.id)
china = Country.create!(name: "China", continent_id: asia.id)
cyprus = Country.create!(name: "Cyprus", continent_id: asia.id)
georgia = Country.create!(name: "Georgia", continent_id: asia.id)
india = Country.create!(name: "India", continent_id: asia.id)
indonesia = Country.create!(name: "Indonesia", continent_id: asia.id)
iran = Country.create!(name: "Iran", continent_id: asia.id)
iraq = Country.create!(name: "Iraq", continent_id: asia.id)
israel = Country.create!(name: "Israel", continent_id: asia.id)
japan = Country.create!(name: "Japan", continent_id: asia.id)
jordan = Country.create!(name: "Jordan", continent_id: asia.id)
kazakhstan = Country.create!(name: "Kazakhstan", continent_id: asia.id)
kuwait = Country.create!(name: "Kuwait", continent_id: asia.id)
kyrgyzstan = Country.create!(name: "Kyrgyzstan", continent_id: asia.id)
laos = Country.create!(name: "Laos", continent_id: asia.id)
lebanon = Country.create!(name: "Lebanon", continent_id: asia.id)
malaysia = Country.create!(name: "Malaysia", continent_id: asia.id)
maldives = Country.create!(name: "Maldives", continent_id: asia.id)
mongolia = Country.create!(name: "Mongolia", continent_id: asia.id)
myanmar = Country.create!(name: "Myanmar", continent_id: asia.id)
nepal = Country.create!(name: "Nepal", continent_id: asia.id)
north_korea = Country.create!(name: "North Korea", continent_id: asia.id)
oman = Country.create!(name: "Oman", continent_id: asia.id)
pakistan = Country.create!(name: "Pakistan", continent_id: asia.id)
palestine = Country.create!(name: "Palestine", continent_id: asia.id)
philippines = Country.create!(name: "Philippines", continent_id: asia.id)
qatar = Country.create!(name: "Qatar", continent_id: asia.id)
saudi_arabia = Country.create!(name: "Saudi Arabia", continent_id: asia.id)
singapore = Country.create!(name: "Singapore", continent_id: asia.id)
south_korea = Country.create!(name: "South Korea", continent_id: asia.id)
sri_lanka = Country.create!(name: "Sri Lanka", continent_id: asia.id)
syria = Country.create!(name: "Syria", continent_id: asia.id)
tajikistan = Country.create!(name: "Tajikistan", continent_id: asia.id)
thailand = Country.create!(name: "Thailand", continent_id: asia.id)
timor_leste = Country.create!(name: "Timor-Leste", continent_id: asia.id)
turkey = Country.create!(name: "Turkey", continent_id: asia.id)
turkmenistan = Country.create!(name: "Turkmenistan", continent_id: asia.id)
uae = Country.create!(name: "United Arab Emirates", continent_id: asia.id)
uzbekistan = Country.create!(name: "Uzbekistan", continent_id: asia.id)
vietnam = Country.create!(name: "Vietnam", continent_id: asia.id)
yemen = Country.create!(name: "Yemen", continent_id: asia.id)

#North America

antigua_barbuda = Country.create!(name: "Antigua and Barbuda", continent_id: north_america.id)
bahamas = Country.create!(name: "Bahamas", continent_id: north_america.id)
barbados = Country.create!(name: "Barbados", continent_id: north_america.id)
belize = Country.create!(name: "Belize", continent_id: north_america.id)
canada = Country.create!(name: "Canada", continent_id: north_america.id)
costa_rica = Country.create!(name: "Costa Rica", continent_id: north_america.id)
cuba = Country.create!(name: "Cuba", continent_id: north_america.id)
dominica = Country.create!(name: "Dominica", continent_id: north_america.id)
dominican_republic = Country.create!(name: "Dominican Republic", continent_id: north_america.id)
el_salvador = Country.create!(name: "El Salvador", continent_id: north_america.id)
grenada = Country.create!(name: "Grenada", continent_id: north_america.id)
guatemala = Country.create!(name: "Guatemala", continent_id: north_america.id)
haiti = Country.create!(name: "Haiti", continent_id: north_america.id)
honduras = Country.create!(name: "Honduras", continent_id: north_america.id)
jamaica = Country.create!(name: "Jamaica", continent_id: north_america.id)
mexico = Country.create!(name: "Mexico", continent_id: north_america.id)
nicaragua = Country.create!(name: "Nicaragua", continent_id: north_america.id)
panama = Country.create!(name: "Panama", continent_id: north_america.id)
saint_kitts_nevis = Country.create!(name: "Saint Kitts and Nevis", continent_id: north_america.id)
saint_lucia = Country.create!(name: "Saint Lucia", continent_id: north_america.id)
saint_vincent_grenadines = Country.create!(name: "Saint Vincent and the Grenadines", continent_id: north_america.id)
trinidad_tobago = Country.create!(name: "Trinidad and Tobago", continent_id: north_america.id)
usa = Country.create!(name: "United States of America", continent_id: north_america.id)

#South America

argentina = Country.create!(name: "Argentina", continent_id: south_america.id)
bolivia = Country.create!(name: "Bolivia", continent_id: south_america.id)
brazil = Country.create!(name: "Brazil", continent_id: south_america.id)
chile = Country.create!(name: "Chile", continent_id: south_america.id)
colombia = Country.create!(name: "Colombia", continent_id: south_america.id)
ecuador = Country.create!(name: "Ecuador", continent_id: south_america.id)
falkland_islands = Country.create!(name: "Falkland Islands", continent_id: south_america.id)
french_guiana = Country.create!(name: "French Guiana", continent_id: south_america.id)
guyana = Country.create!(name: "Guyana", continent_id: south_america.id)
paraguay = Country.create!(name: "Paraguay", continent_id: south_america.id)
peru = Country.create!(name: "Peru", continent_id: south_america.id)
suriname = Country.create!(name: "Suriname", continent_id: south_america.id)
uruguay = Country.create!(name: "Uruguay", continent_id: south_america.id)
venezuela = Country.create!(name: "Venezuela", continent_id: south_america.id)

#Europe

albania = Country.create!(name: "Albania", continent_id: europe.id)
andorra = Country.create!(name: "Andorra", continent_id: europe.id)
austria = Country.create!(name: "Austria", continent_id: europe.id)
belarus = Country.create!(name: "Belarus", continent_id: europe.id)
belgium = Country.create!(name: "Belgium", continent_id: europe.id)
bosnia_herzegovina = Country.create!(name: "Bosnia and Herzegovina", continent_id: europe.id)
bulgaria = Country.create!(name: "Bulgaria", continent_id: europe.id)
croatia = Country.create!(name: "Croatia", continent_id: europe.id)
czech_republic = Country.create!(name: "Czech Republic", continent_id: europe.id)
denmark = Country.create!(name: "Denmark", continent_id: europe.id)
estonia = Country.create!(name: "Estonia", continent_id: europe.id)
finland = Country.create!(name: "Finland", continent_id: europe.id)
france = Country.create!(name: "France", continent_id: europe.id)
germany = Country.create!(name: "Germany", continent_id: europe.id)
greece = Country.create!(name: "Greece", continent_id: europe.id)
holy_see = Country.create!(name: "Holy See", continent_id: europe.id)
hungary = Country.create!(name: "Hungary", continent_id: europe.id)
iceland = Country.create!(name: "Iceland", continent_id: europe.id)
ireland = Country.create!(name: "Ireland", continent_id: europe.id)
italy = Country.create!(name: "Italy", continent_id: europe.id)
latvia = Country.create!(name: "Latvia", continent_id: europe.id)
liechtenstein = Country.create!(name: "Liechtenstein", continent_id: europe.id)
lithuania = Country.create!(name: "Lithuania", continent_id: europe.id)
luxembourg = Country.create!(name: "Luxembourg", continent_id: europe.id)
malta = Country.create!(name: "Malta", continent_id: europe.id)
moldova = Country.create!(name: "Moldova", continent_id: europe.id)
monaco = Country.create!(name: "Monaco", continent_id: europe.id)
montenegro = Country.create!(name: "Montenegro", continent_id: europe.id)
netherlands = Country.create!(name: "Netherlands", continent_id: europe.id)
north_macedonia = Country.create!(name: "North Macedonia", continent_id: europe.id)
norway = Country.create!(name: "Norway", continent_id: europe.id)
poland = Country.create!(name: "Poland", continent_id: europe.id)
portugal = Country.create!(name: "Portugal", continent_id: europe.id)
romania = Country.create!(name: "Romania", continent_id: europe.id)
russia = Country.create!(name: "Russia", continent_id: europe.id)
san_marino = Country.create!(name: "San Marino", continent_id: europe.id)
serbia = Country.create!(name: "Serbia", continent_id: europe.id)
slovakia = Country.create!(name: "Slovakia", continent_id: europe.id)
slovenia = Country.create!(name: "Slovenia", continent_id: europe.id)
spain = Country.create!(name: "Spain", continent_id: europe.id)
sweden = Country.create!(name: "Sweden", continent_id: europe.id)
switzerland = Country.create!(name: "Switzerland", continent_id: europe.id)
ukraine = Country.create!(name: "Ukraine", continent_id: europe.id)
united_kingdom = Country.create!(name: "United Kingdom", continent_id: europe.id)

#Australia and Oceania

australia = Country.create!(name: "Australia", continent_id: oceania.id)
fiji = Country.create!(name: "Fiji", continent_id: oceania.id)
kiribati = Country.create!(name: "Kiribati", continent_id: oceania.id)
marshall_islands = Country.create!(name: "Marshall Islands", continent_id: oceania.id)
micronesia = Country.create!(name: "Micronesia", continent_id: oceania.id)
nauru = Country.create!(name: "Nauru", continent_id: oceania.id)
new_zealand = Country.create!(name: "New Zealand", continent_id: oceania.id)
palau = Country.create!(name: "Palau", continent_id: oceania.id)
papua_new_guinea = Country.create!(name: "Papua New Guinea", continent_id: oceania.id)
samoa = Country.create!(name: "Samoa", continent_id: oceania.id)
solomon_islands = Country.create!(name: "Solomon Islands", continent_id: oceania.id)
tonga = Country.create!(name: "Tonga", continent_id: oceania.id)
tuvalu = Country.create!(name: "Tuvalu", continent_id: oceania.id)
vanuatu = Country.create!(name: "Vanuatu", continent_id: oceania.id)

#Africa

algeria = Country.create!(name: "Algeria", continent_id: africa.id)
angola = Country.create!(name: "Angola", continent_id: africa.id)
benin = Country.create!(name: "Benin", continent_id: africa.id)
botswana = Country.create!(name: "Botswana", continent_id: africa.id)
burkina_faso = Country.create!(name: "Burkina Faso", continent_id: africa.id)
burundi = Country.create!(name: "Burundi", continent_id: africa.id)
cabo_verde = Country.create!(name: "Cabo Verde", continent_id: africa.id)
cameroon = Country.create!(name: "Cameroon", continent_id: africa.id)
central_africa_republic = Country.create!(name: "Central Africa Republic", continent_id: africa.id)
chad = Country.create!(name: "Chad", continent_id: africa.id)
comoros = Country.create!(name: "Comoros", continent_id: africa.id)
congo = Country.create!(name: "Congo", continent_id: africa.id)
cote_d_ivoire = Country.create!(name: " Côte d'Ivoire", continent_id: africa.id)
djibouti = Country.create!(name: "Djibouti", continent_id: africa.id)
dr_congo = Country.create!(name: "Democratic Republic of the Congo", continent_id: africa.id)
egypt = Country.create!(name: "Egypt", continent_id: africa.id)
equatorial_guinea = Country.create!(name: "Equatorial Guinea", continent_id: africa.id)
eritrea = Country.create!(name: "Eritrea", continent_id: africa.id)
eswatini = Country.create!(name: "Eswatini", continent_id: africa.id)
ethiopia = Country.create!(name: "Ethiopia", continent_id: africa.id)
gabon = Country.create!(name: "Gabon", continent_id: africa.id)
gambia = Country.create!(name: "Gambia", continent_id: africa.id)
ghana = Country.create!(name: "Ghana", continent_id: africa.id)
guinea = Country.create!(name: "Guinea", continent_id: africa.id)
guinea_bissau = Country.create!(name: "Guinea Bissau", continent_id: africa.id)
kenya = Country.create!(name: "Kenya", continent_id: africa.id)
lesotho = Country.create!(name: "Lesotho", continent_id: africa.id)
liberia = Country.create!(name: "Liberia", continent_id: africa.id)
libya = Country.create!(name: "Libya", continent_id: africa.id)
madagascar = Country.create!(name: "Madagascar", continent_id: africa.id)
malawi = Country.create!(name: "Malawi", continent_id: africa.id)
mali = Country.create!(name: "Mali", continent_id: africa.id)
mauritania = Country.create!(name: "Mauritania", continent_id: africa.id)
mauritius = Country.create!(name: "Mauritius", continent_id: africa.id)
morocco = Country.create!(name: "Morocco", continent_id: africa.id)
mozambique = Country.create!(name: "Mozambique", continent_id: africa.id)
namibia = Country.create!(name: "Namibia", continent_id: africa.id)
niger = Country.create!(name: "Niger", continent_id: africa.id)
nigeria = Country.create!(name: "Nigeria", continent_id: africa.id)
rwanda = Country.create!(name: "Rwanda", continent_id: africa.id)
sao_tome_principe = Country.create!(name: "Sao Tome and Principe", continent_id: africa.id)
senegal = Country.create!(name: "Senegal", continent_id: africa.id)
seychelles = Country.create!(name: "Seychelles", continent_id: africa.id)
sierra_leone = Country.create!(name: "Sierra Leone", continent_id: africa.id)
somalia = Country.create!(name: "Somalia", continent_id: africa.id)
south_africa = Country.create!(name: "South Africa", continent_id: africa.id)
south_sudan = Country.create!(name: "South Sudan", continent_id: africa.id)
sudan = Country.create!(name: "Sudan", continent_id: africa.id)
tanzania = Country.create!(name: "Tanzania", continent_id: africa.id)
togo = Country.create!(name: "Togo", continent_id: africa.id)
tunisia = Country.create!(name: "Tunisia", continent_id: africa.id)
uganda = Country.create!(name: "Uganda", continent_id: africa.id)
zambia = Country.create!(name: "Zambia", continent_id: africa.id)
zimbabwe = Country.create!(name: "Zimbabwe", continent_id: africa.id)

#Antarctica

antarctica = Country.create!(name: "Antarctica", continent_id: africa.id)

puts "Done seeding countries..."
